Repository slack-go/slack, pull requests merged in 2020-12, with the labels that each got.

#843 reminders time field fix
  reminders.go
Labels: bug

#788 Resolve: Revert changes to json tags in Attachment's Text field
  attachments.go
  attachments_test.go
  chat_test.go
Labels: bug

#854 Fix unintended json marshalling error
  block_action.go
Labels: api breaking change

#761 [Feat] conversations.mark
  conversation.go
  conversation_test.go
Labels: enhancement
