Repository slack-go/slack, pull requests merged in 2021-10, with the labels that each got.

#986 add message subType constants from https://api.slack.com/events/message
  messages.go
  messages_test.go
Labels: enhancement, RTM API, Web API

#978 Add TeamJoinEvent
  slackevents/inner_events.go
Labels: enhancement

#971 Change the regular field `apiClient` in `socketmode.Client` to an embedded struct.
  socketmode/client.go
  socketmode/socketmode.go
Labels: api cleanup

#976 Update users example
  examples/modal_users/users.go
Labels: feedback given, example
