Repository slack-go/slack, pull requests merged in 2021-04, with the labels that each got.

#908 Seems the token was missing from the request.
  files.go
  misc.go
  users.go
Labels: bugfix, spec changes

#918 Add timepicker to UnmarshalJSON
  block_conv.go
Labels: bugfix

#831 Change ActionType to public
  attachments.go
  block.go
  interactions.go
  interactions_test.go
Labels: api cleanup

#894 Make UserID optional in GetUserProfile()
  users.go
  users_test.go
Labels: breaking changes

#910 Remove deprecated methods
  channels.go
  examples/channels/channels.go
  examples/groups/groups.go
  examples/ims/ims.go
  examples/pins/pins.go
  examples/reactions/reactions.go
  groups.go
  im.go
  slacktest/handlers.go
  slacktest/handlers_test.go
  slacktest/server.go
Labels: api cleanup, spec changes

#832 Change type of `ExcludeArchived` field to bool in `GetConversationsParameters`
  conversation.go
Labels: api cleanup, breaking changes

#923 [socketmode] Add methods with passing context
  socketmode/client.go
  socketmode/socket_mode_managed_conn.go
  socketmode/socket_mode_managed_conn_test.go
  socketmode/socketmode.go
Labels: SocketMode, enhancement

#931 Support response_urls field for view_submission payload
  interactions_test.go
  views.go
Labels: enhancement
