Repository slack-go/slack, pull requests merged in 2021-07, with the labels that each got.

#942 slacktest: Fix broken json if newline in text
  slacktest/handlers.go
Labels: api cleanup

#946 Add GetConversationsParameters.TeamID
  conversation.go
Labels: Web API, enhancement

#951 Use GET /audit/v1/logs instead of POST
  audit.go
Labels: Web API, api cleanup

#888 add thread_ts to container
  interactions.go
  interactions_test.go
Labels: enhancement, spec undocumented
