Repository slack-go/slack, pull requests merged in 2021-03, with the labels that each got.

#900 Expose ReplyTo information in ack error events.
  websocket_internals.go
  websocket_managed_conn.go
Labels: enhancement

#880 Add support for "channel_created" in the Events API.
  slackevents/inner_events.go
Labels: enhancement, feedback given

#838 Make possible to get authorized user's profile providing empty userID to GetUserProfileContext
  users.go
Labels: api cleanup
