Repository slack-go/slack, pull requests merged in 2021-11, with the labels that each got.

#991 Support Rich Text blocks
  block.go
  block_conv.go
  block_rich_text.go
  block_rich_text_test.go
Labels: enhancement

#995 fix: Don't add API token as a query string in `users.setPhoto`
  users.go
  users_test.go
Labels: bugfix

#999 link_shared `message_ts` field isn't always a number
  slackevents/inner_events.go
  slackevents/inner_events_test.go
Labels: breaking changes, bugfix
