Repository slack-go/slack, pull requests merged in 2022-07, with the labels that each got.

#1083 Metadata Support
  chat.go
  chat_test.go
  conversation.go
  messages.go
  metadata.go
Labels: enhancement

#1086 Add option to detect unmapped error
  websocket_managed_conn.go
  websocket_managed_conn_test.go
Labels: api cleanup

#1060 add: workflows.stepCompleted and workflwows.stepFailed support
  workflow_step_execute.go
  workflow_step_execute_test.go
Labels: enhancement, Web API

#1082 Fixes updateUserGroup cannot clear the description and the default channels
  usergroups.go
  usergroups_test.go
Labels: bugfix, Web API
