Repository slack-go/slack, pull requests merged in 2022-06, with the labels that each got.

#904 Socketmode Middleware Design Pattern
  README.md
  examples/socketmode_handler/socketmode_handler.go
  slackevents/inner_events.go
  slackevents/parsers.go
  slacktest/data.go
  slacktest/handlers.go
  slacktest/server.go
  socketmode/socketmode_handler.go
  socketmode/socketmode_handler_test.go
  socketmode/socketmode_test.go
Labels: enhancement, needs review, breaking changes, feedback given, SocketMode, experimental

#1064 Fix field types in `SubteamMembersChangedEvent`
  websocket_subteam.go
Labels: breaking changes, spec changes, spec undocumented

#1052 Uniformize event_ts support on inner events
  slackevents/inner_events.go
  socketmode/socketmode_test.go
Labels: breaking changes, api cleanup

#970 Add field to inputblock
  block_input.go
  block_input_test.go
  examples/modal/modal.go
  examples/modal_users/users.go
  interactions_test.go
  views_test.go
Labels: enhancement, breaking changes

#1067 Remove full event details from UnmarshallingErrorEvent
  websocket_managed_conn.go
Labels: api cleanup

#1069 Add `Permalink` to Msg struct
  messages.go
Labels: enhancement
