Repository slack-go/slack, pull requests merged in 2022-04, with the labels that each got.

#1055 Add fluent `WithConfirm` for `ButtonBlockElement`s
  block_element.go
Labels: api cleanup

#1054 `WithStyle` for `ConfirmationBlockObject`s should be fluent
  block_object.go
Labels: api cleanup

#1047 Added Details field to Audit event entries
  audit.go
Labels: enhancement, feedback given

#1044 Add `bookmarks.<add|edit|remove|list>` support
  bookmarks.go
  bookmarks_test.go
Labels: enhancement, Web API
