Repository slack-go/slack, pull requests merged in 2022-12, with the labels that each got.

#1129 Fix WorkflowStepCompletedRequest options handling
  workflow_step_execute.go
Labels: bugfix, Web API

#1139 add include_all_metadata to conversations.replies API
  conversation.go
Labels: enhancement

#1134 Add team_id as a parameter to the users.conversations API method
  conversation.go
Labels: enhancement, Web API

#1132 feat: add number input block element
  block_conv.go
  block_element.go
  block_element_test.go
Labels: enhancement

#1118 add GetOtherTeam method
  team.go
Labels: enhancement, feedback given

#1140 add block elements for email_text_input and url_text_input
  block_conv.go
  block_element.go
  block_element_test.go
Labels: enhancement

#1095 Expose reactionItem and reactionEvent
  websocket_reactions.go
Labels: api cleanup

#1097 Support team.profile.get method
  team.go
  team_test.go
  users.go
Labels: enhancement, Web API

#1131 fix: change type of timestamp
  block_rich_text.go
  block_rich_text_test.go
Labels: breaking changes, bugfix

#989 Add include_num_members support to conversation.info request
  conversation.go
  conversation_test.go
Labels: enhancement, breaking changes

#1119 Add ListTeams and TeamAccess{Granted,Revoked}Events and fix missing enterprise ID
  auth.go
  auth_test.go
  conversation.go
  conversation_test.go
  examples/pins/pins.go
  slackevents/inner_events.go
  slackevents/outer_events.go
  slackevents/parsers.go
  slacktest/handlers_test.go
Labels: enhancement, breaking changes

#1148 Add FileUploadV2 function to avoid server side file timeouts
  files.go
  files_test.go
  misc.go
Labels: enhancement, bugfix, Web API

#1147 fix: change period to comma
  block_rich_text.go
Labels: api cleanup, bugfix

#1145 add datetimepicker component
  block.go
  block_conv.go
  block_element.go
  block_element_test.go
Labels: enhancement
