Repository slack-go/slack, pull requests merged in 2022-08, with the labels that each got.

#1098 fix some simple typos
  misc.go
  slackevents/outer_events.go
  slackevents/parsers.go
  slackevents/parsers_test.go
Labels: documentation, example

#1099 Fix GoDoc grammers
  dialog_text.go
  internal/backoff/backoff.go
  socketmode/request.go
  stars.go
Labels: documentation

#1096 Add metadata related event types
  slackevents/inner_events.go
  slackevents/inner_events_test.go
Labels: enhancement
