Repository slack-go/slack, pull requests merged in 2022-09, with the labels that each got.

#1109 fix: UploadFileContext not calling api.AuthTestContext
  files.go
Labels: api cleanup

#1106 Handle null value in JSONTime
  info.go
  info_test.go
Labels: bugfix

#1094 Honor deadman timer, fixes #1093
  socketmode/socket_mode_managed_conn.go
Labels: SocketMode, bugfix

#1080 sharedLinks struct should be exported
  slackevents/inner_events.go
  slackevents/inner_events_test.go
Labels: api cleanup
