Repository slack-go/slack, pull requests merged in 2023-04, with the labels that each got.

#1188 Add actions/stale action
  .github/workflows/stale.yaml
Labels: misc

#1165 socketmode remove duplicate debug logging
  socketmode/socket_mode_managed_conn.go
Labels: api cleanup

#1193 Bump up golangci-lint and its action to latest
  .github/workflows/test.yml
Labels: misc

#1169 Implement context-aware RunEventLoop
  socketmode/socketmode_handler.go
Labels: needs review, api cleanup, SocketMode

#1180 Add ReplyUsers to Msg Struct
  messages.go
Labels: enhancement, needs review

#1170 socketmode: awaiting of message receiver goroutine in run method to avoid panics
  socketmode/socket_mode_managed_conn.go
Labels: needs review, SocketMode, bugfix

#1164 socketmode example: use embedded api client in socketmode client
  examples/socketmode/socketmode.go
Labels: example
