Repository slack-go/slack, pull requests merged in 2024-11, with the labels that each got.

#1331 feat: Slack AI & Assistants Compatibility
  assistant.go
  assistant_test.go
  block_section.go
  slackevents/inner_events.go
  slackevents/inner_events_test.go
Labels: enhancement, RTM API, Web API

#1344 fix: Assistant Prompts and Status, send channel_id with request
  assistant.go
Labels: bugfix, Web API

#1341 fix: Don't require `skin_tone` for rich text emoji element
  block_rich_text.go
  block_rich_text_test.go
Labels: bugfix

#1153 fix: ScheduleMessage not returning scheduled_message_id
  chat.go
Labels: enhancement, api cleanup, Web API
