Repository slack-go/slack, pull requests merged in 2024-08, with the labels that each got.

#1310 chore: replace ioutil with io or os package
  chat.go
  chat_test.go
  examples/dialog/dialog.go
  examples/eventsapi/events.go
  examples/modal/modal.go
  examples/slash/slash.go
  examples/workflow_step/handler.go
  examples/workflow_step/middleware.go
  files_test.go
  misc.go
  reminders_test.go
  slacktest/handlers.go
  users_test.go
  webhooks.go
Labels: optimize

#1312 feat: add file access field to file struct for slackevents
  slackevents/inner_events.go
Labels: enhancement, RTM API, SocketMode

#1311 feat: Add slack_file to image block
  block_image.go
Labels: enhancement

#1306 feat: Events api reconcilation
  slackevents/inner_events.go
  slackevents/inner_events_test.go
Labels: enhancement, RTM API

#1308 feat: Add support for parsing AppRateLimited events
  slackevents/parsers.go
  slackevents/parsers_test.go
Labels: enhancement, RTM API, SocketMode

#1228 feat: Add Properties.Canvas to Channel
  channels.go
  conversation.go
  conversation_test.go
Labels: enhancement, Web API

#1117 fix: create multipart form when multipart request
  misc.go
  remotefiles.go
Labels: bugfix, Web API

#1315 ci: Add go v1.23 to test matrix (test.yml)
  .github/workflows/test.yml
Labels: misc

#1314 ci: Bump GitHub Actions to Latest Versions
  .github/workflows/stale.yaml
  .github/workflows/test.yml
Labels: misc

#1316 docs: fix deprecated comment for UploadFile and UploadFileContext
  files.go
Labels: documentation
