Repository slack-go/slack, pull requests merged in 2024-07, with the labels that each got.

#1208 Add UnfurlLinks and UnfurlMedia to WebhookMessage
  webhooks.go
Labels: enhancement, Web API

#1211 chore: slice replace loop
  reminders.go
Labels: easy, optimize

#1232 Add isReadOnly property to Conversation struct
  conversation.go
Labels: bugfix, Web API

#1293 chore: make channel optional on `UploadFileV2`
  files.go
  files_test.go
Labels: enhancement, Web API

#1300 chore: Adding Deprecation Notice for files.upload
  files.go
Labels: needs review, api cleanup, Web API

#1298 ci: Adding Go Test Coverage for 1.21 and 1.22
  .github/workflows/test.yml
Labels: needs review, easy

#1299 docs: Updating Inline Docs and API References
  apps.go
  auth.go
  bookmarks.go
  bots.go
  chat.go
  conversation.go
  dnd.go
  emoji.go
  files.go
  manifests.go
  oauth.go
  pins.go
  reactions.go
  reminders.go
  remotefiles.go
  stars.go
  team.go
  tokens.go
  usergroups.go
  users.go
  views.go
  workflow_step.go
Labels: documentation

#1201 docs: Add an example demonstrating correct usage of GetUsersPaginated
  examples/pagination/pagination.go
Labels: example, Web API

#1303 docs: Adding an example for AddRemoteFile and DeleteFile
  examples/files_remote/files_remote.go
Labels: example, Web API

#1302 docs: Adding an example for ConversationHistory
  examples/conversation_history/conversation_history.go
Labels: example, Web API

#1307 feat(slackevents): Support metadata in MessageEvent
  slackevents/inner_events.go
  slackevents/inner_events_test.go
Labels: enhancement, SocketMode
