Repository slack-go/slack, pull requests merged in 2025-05, with the labels that each got.

#1412 RichTextSectionLinkElement Text omitempty
  block_rich_text.go
Labels: bugfix

#1413 Add interaction callback parser
  interactions.go
  interactions_test.go
Labels: enhancement

#1417 Subteam events in socketmode should have their 'Count' entries as numbers, not strings
  .gitignore
  examples/socketmode/socketmode.go
  examples/socketmode_handler/socketmode_handler.go
  slackevents/inner_events.go
  slackevents/inner_events_test.go
Labels: bugfix

#1416 [chore]: support only the last 3 versions of go
  .github/workflows/test.yml
  go.mod
Labels: dependencies, ci, github_actions

#1418 fix: don't allow emoji with `mrkdwn`
  attachments_test.go
  block_object.go
  block_object_test.go
  block_section_test.go
  examples/blocks/README.md
  interactions_test.go
Labels: bugfix

#1422 feat!: expose `UploadToURL` (from `uploadToURL`)
  examples/files/files.go
  examples/files/multiple_files/batman.txt
  examples/files/multiple_files/multiple_files.go
  examples/files/multiple_files/superman.txt
  files.go
  files_test.go
Labels: enhancement, breaking changes, bugfix, feature request

#1425 fix: tighten permissions for the test workflow
  .github/workflows/stale.yml
  .github/workflows/test.yml
Labels: ci

#1431 chore: add CI test status badge to README
  README.md
Labels: documentation
