Repository slack-go/slack, pull requests merged in 2025-03, with the labels that each got.

#1382 chore: remove unused GO111MODULE from the tests
  .github/workflows/test.yml
Labels: misc

#1357 [fix] function execution events accept interfaces not strings
  examples/function/function.go
  slackevents/inner_events.go
  slackevents/inner_events_test.go
Labels: breaking changes

#1322 Implement PublishViewContextV2 to keep hash optional
  views.go
Labels: enhancement, breaking changes, Web API

#1350 DEPRECATION!: Legacy Workflows Deprecation
  examples/workflow_step/README.md
  examples/workflow_step/go.mod
  examples/workflow_step/go.sum
  examples/workflow_step/handler.go
  examples/workflow_step/main.go
  examples/workflow_step/middleware.go
  interactions.go
  slackevents/inner_events.go
  slackevents/inner_events_test.go
  workflow_step.go
  workflow_step_execute.go
  workflow_step_execute_test.go
  workflow_step_test.go
Labels: breaking changes, spec changes, Web API

#1354 fix: Allow `emoji` value in plain text blocks to be null
  attachments_test.go
  block_object.go
  block_object_test.go
  block_section_test.go
  chat_test.go
  interactions_test.go
  views_test.go
  webhooks_test.go
Labels: breaking changes

#1386 chore: bump golangci to 1.63.4
  .github/workflows/test.yml
  .golangci.yml
Labels: dependencies, ci

#1391 Fix message event struct
  messages.go
  slackevents/inner_events.go
  slackevents/inner_events_test.go
Labels: breaking changes

#1398 feat: add a bunch of missing params to usergroups.* calls
  usergroups.go
Labels: enhancement, Web API, feature request

#1401 Add some missing admin.conversations endpoints
  admin_conversations.go
  admin_conversations_test.go
Labels: enhancement, Web API
