Repository slack-go/slack, pull requests merged in 2025-06, with the labels that each got.

#1437 feat: add channel_unshared event
  slackevents/inner_events.go
  slackevents/inner_events_test.go
Labels: enhancement

#1443 feat: return Errors field in SlackErrorResponse
  examples/conversations_invite/conversations_invite.go
  misc.go
  misc_test.go
Labels: enhancement

#1445 doc: add README.md to examples/eventsapi
  examples/eventsapi/README.md
Labels: documentation

#1444 Support Slack Files in ImageBlockElement
  block_element.go
  block_element_test.go
  block_image.go
  block_image_test.go
Labels: enhancement

#1451 feat: add ability to add file ids when updating a message
  chat.go
  chat_test.go
Labels: enhancement, easy
